---

- name: copy simplesnap scripts
  copy:
    src: "{{ item }}"
    dest: /usr/local/bin/
    owner: root
    group: root
    mode: "a+x"
  with_items:
    - simplesnap
    - simplesnapwrap

- name: create ssh key for simplesnap
  user:
    name: "root"
    generate_ssh_key: yes
    ssh_key_bits: "2048"
    ssh_key_file: ".ssh/simplesnap"

- name: Create cron task for polling backups
  cron:
    minute: "{{ item.minute|default('23') }}"
    hour: "{{ item.hour|default('01') }}"
    day: "{{ item.day|default('*') }}"
    month: "{{ item.month|default('*') }}"
    dow: "{{ item.dow|default('*') }}"
    user: "{{ item.user|default(user) }}"
    name: "{{ item.cron_file|default(cron_file) }}"
    cron_file: "{{ item.cron_file|default(cron_file) }}"
    job: "/usr/local/sbin/simplesnap {{ item.remotehost }} --setname {{ item.setname|default('mainset') }} --store {{ item.store|default('tank/backup') }}"
    backup: yes
    state: present
  with_items: "{{ simplesnap_jobs }}"
